---

- hosts: all
  become: true 
  tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 pachage
    apt:
      name: apache2
      state: latest

  - name: add php support for apache
    apt:
      name: libapache2-mod-php 
      state: latest

  - name: add neovim and vim and neofetch
    apt:
      name: 
        - neovim
        - vim
        - neofetch
      state: latest
    when: ansible_distribution == "Ubuntu"

