---

- hosts: all
  become: true 
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 pachage
    apt:
      name: apache2
      state: latest

  - name: add php support for apache
    apt:
      name: libapache2-mod-php 
      state: latest

  - name: add neovim and vim and neofetch
    tags: neovim,vim,neofetch
    apt:
      name: 
        - neovim
        - vim
        - neofetch
      state: latest
    when: ansible_distribution == "Ubuntu"
 
  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true 
  tasks:

  - name: install mariadb packahe (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
  
